---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: echo-poc-pipeline
  namespace: pkumari-tenant
  labels:
    appstudio.openshift.io/component: slpsd8qa9-go
    appstudio.openshift.io/application: simple-goapp
spec:
  tasks:
    - name: echo-test
      taskSpec:
        steps:
          - name: test
            image: quay.io/openshift-pipeline/ci
            script: |
              #!/usr/bin/env bash

              words=("hello" "hi")

              # create the pipeline
              oc create -f https://github.com/prietyc123-qe-org/slpsd8qa9-go/blob/main/integration-tests/pipelines/echo-test-pipeline.yaml

              # Loop through the array and print each element
              for word in "${words[@]}"
              do
                tkn pipeline start echo-test-pipeline --param TEST="$word"
              done
