apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: echo-poc-pipeline
  namespace: pkumari-tenant
  labels:
    appstudio.openshift.io/component: slpsd8qa9-go
    appstudio.openshift.io/application: simple-goapp
spec:
  tasks:
    - name: create-echo-test-pipeline
      taskSpec:
        steps:
          - name: create-pipeline
            image: quay.io/openshift-pipeline/ci
            script: |
              #!/usr/bin/env bash
              echo "Creating the echo-test-pipeline"
              oc create -f https://raw.githubusercontent.com/prietyc123-qe-org/slpsd8qa9-go/main/integration-tests/pipelines/echo-test-pipeline.yaml

    - name: start-echo-test-pipeline
      runAfter: 
        - create-echo-test-pipeline
      taskSpec:
        steps:
          - name: start-pipeline
            image: quay.io/openshift-pipeline/ci
            script: |
              #!/usr/bin/env bash
              words=("hello" "hi")
              # Start the created pipeline with different parameters
              for word in "${words[@]}"
              do
                tkn pipeline start echo-test-pipeline --param TEST="$word"
              done
